web:
      build: .
      environment:
        XDEBUG_CONFIG: "HOSTIP"
        LOG_STDOUT: "true"
        LOG_STDERR: "true"
        LOG_LEVEL: "debug"
      volumes:
      - "./:/var/www/html"
      ports:
        - "8080:80"
virtuoso:
  image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
  environment:
    SPARQL_UPDATE: "true"
    DEFAULT_GRAPH: "http://citeapp.ch"
  volumes:
    - "./data/virtuoso:/data"
  ports:
    - "8890:8890"
    - "1111:1111"


neo4j:
  image: neo4j:3.4
  environment:
    NEO4J_AUTH: "neo4j/password"
  volumes:
  - "./data/neo4j:/data"
  ports:
  - "7474:7474"
  #for websocket of neo4j WebUi
  - "7687:7687"