web:
      build: .
      environment:
        XDEBUG_CONFIG: "HOSTIP"
        LOG_STDOUT: "true"
        LOG_STDERR: "true"
        LOG_LEVEL: "debug"
      volumes:
      - "./:/var/www/html"
      ports:
        - "8080:80"
db:
  image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
  environment:
    SPARQL_UPDATE: "true"
    DEFAULT_GRAPH: "http://citeapp.ch"
  volumes:
    - "./data/virtuoso:/data"
  ports:
    - "8890:8890"
    - "1111:1111"